/* eslint-disable */
/** AUTO-GENERATED by scripts/generate-matrix-data.mjs. Do not edit by hand. */
export const MATRIX_DATA = {
  "generated_from": [
    "feature_matrix.yaml",
    "package_versions.yaml"
  ],
  "feature_definitions": {
    "crash_fix_threadlocal": {
      "display_name": "Android API 25 crash fix",
      "description": "Fixed a crash on Android API 25 and below caused by use of ThreadLocal.withInitial(), which requires API 26+. Replaced with a method supported on older API levels.",
      "scope": "platform-level",
      "applies_to": "Android packages only, all mediations. Not applicable to any iOS package."
    },
    "discard_timeout_ad": {
      "display_name": "Discard late ad after timeout no-fill",
      "description": "Each placement has a timeout starting when the adapter receives a request. If no ad is served within that timeout, the adapter sends a no-fill to mediation. This fix discards any ad that the underlying GMA (Google Mobile Ads, the demand source, distinct from GAM the mediation platform) demand returns after that no-fill was already sent, since it was previously not being discarded.",
      "scope": "demand-level",
      "applies_to": "Every package, all frameworks, all platforms, all mediations, since GMA sits underneath as demand regardless of which mediation platform is on top."
    },
    "banner_ad_refresh": {
      "display_name": "Banner ad refresh",
      "description": "Refreshes a banner ad using the same demand tags without a new backend call. Backend-configurable: enable/disable refresh, refresh interval, retry attempts, retry timeout.",
      "scope": "sdk-level",
      "applies_to": "Packages built on a core SDK version that includes this feature."
    },
    "banner_ad_size_optimization": {
      "display_name": "Banner ad size optimization",
      "description": "Previously, mediation would often request an incorrect size, or all sizes, relative to the actual ad container, causing ads that did not fit or overflowed. Fixed by ignoring the mediation-requested size and instead using a backend-configurable ad size.",
      "scope": "sdk-level",
      "applies_to": "Packages built on a core SDK version that includes this feature."
    },
    "updated_classnames": {
      "display_name": "Standardized class names",
      "description": "Standardization of adapter class names across mediations.",
      "scope": "adapter-level",
      "applies_to": "Each adapter individually, as each is rebuilt."
    }
  },
  "feature_order": [
    "crash_fix_threadlocal",
    "discard_timeout_ad",
    "banner_ad_refresh",
    "banner_ad_size_optimization",
    "updated_classnames"
  ],
  "products": [
    {
      "id": "ca-gma",
      "name": "Custom Adapter GMA SDK",
      "package_count": 36,
      "packages": [
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Native Android AdMob",
          "framework": "Native",
          "platform": "Android",
          "mediation": "AdMob",
          "package_version": "v3.0.4",
          "native_built_on": "",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "shipped",
              "confirmed": true,
              "shipped_in_version": "v3.0.4",
              "note": "",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "shipped",
              "confirmed": true,
              "shipped_in_version": "v3.0.4",
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "shipped",
              "confirmed": true,
              "shipped_in_version": "v3.0.4",
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "shipped",
              "confirmed": true,
              "shipped_in_version": "v3.0.4",
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "shipped",
              "confirmed": true,
              "shipped_in_version": "v3.0.4",
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Native Android GAM",
          "framework": "Native",
          "platform": "Android",
          "mediation": "GAM",
          "package_version": "v3.0.1",
          "native_built_on": "",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Native Android AppLovin MAX",
          "framework": "Native",
          "platform": "Android",
          "mediation": "AppLovin MAX",
          "package_version": "v3.0.0",
          "native_built_on": "",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Native Android LevelPlay",
          "framework": "Native",
          "platform": "Android",
          "mediation": "LevelPlay",
          "package_version": "v3.0.2",
          "native_built_on": "",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Native iOS AdMob",
          "framework": "Native",
          "platform": "iOS",
          "mediation": "AdMob",
          "package_version": "v3.0.1",
          "native_built_on": "",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_applicable",
              "confirmed": true,
              "note": "Platform-level feature, Android only.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Native iOS GAM",
          "framework": "Native",
          "platform": "iOS",
          "mediation": "GAM",
          "package_version": "v3.0.0",
          "native_built_on": "",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_applicable",
              "confirmed": true,
              "note": "Platform-level feature, Android only.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Native iOS AppLovin MAX",
          "framework": "Native",
          "platform": "iOS",
          "mediation": "AppLovin MAX",
          "package_version": "v3.0.2",
          "native_built_on": "",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_applicable",
              "confirmed": true,
              "note": "Platform-level feature, Android only.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Native iOS LevelPlay",
          "framework": "Native",
          "platform": "iOS",
          "mediation": "LevelPlay",
          "package_version": "v2.1.13",
          "native_built_on": "",
          "latest": false,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_applicable",
              "confirmed": true,
              "note": "Platform-level feature, Android only.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Flutter Android AdMob",
          "framework": "Flutter",
          "platform": "Android",
          "mediation": "AdMob",
          "package_version": "v3.0.1",
          "native_built_on": "v3.0.2",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Flutter Android GAM",
          "framework": "Flutter",
          "platform": "Android",
          "mediation": "GAM",
          "package_version": "v3.0.0",
          "native_built_on": "v3.0.1",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Flutter Android AppLovin MAX",
          "framework": "Flutter",
          "platform": "Android",
          "mediation": "AppLovin MAX",
          "package_version": "v1.0.3",
          "native_built_on": "v2.1.16",
          "latest": false,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Flutter Android LevelPlay",
          "framework": "Flutter",
          "platform": "Android",
          "mediation": "LevelPlay",
          "package_version": "v1.0.3",
          "native_built_on": "v2.1.16",
          "latest": false,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Flutter iOS AdMob",
          "framework": "Flutter",
          "platform": "iOS",
          "mediation": "AdMob",
          "package_version": "v3.0.1",
          "native_built_on": "v2.1.13",
          "latest": false,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_applicable",
              "confirmed": true,
              "note": "Platform-level feature, Android only.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Flutter iOS GAM",
          "framework": "Flutter",
          "platform": "iOS",
          "mediation": "GAM",
          "package_version": "v3.0.1",
          "native_built_on": "v3.0.0",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_applicable",
              "confirmed": true,
              "note": "Platform-level feature, Android only.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Flutter iOS AppLovin MAX",
          "framework": "Flutter",
          "platform": "iOS",
          "mediation": "AppLovin MAX",
          "package_version": "v3.0.2",
          "native_built_on": "v3.0.1",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_applicable",
              "confirmed": true,
              "note": "Platform-level feature, Android only.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Flutter iOS LevelPlay",
          "framework": "Flutter",
          "platform": "iOS",
          "mediation": "LevelPlay",
          "package_version": "v1.0.3",
          "native_built_on": "v2.1.12",
          "latest": false,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_applicable",
              "confirmed": true,
              "note": "Platform-level feature, Android only.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Unity Android AdMob",
          "framework": "Unity",
          "platform": "Android",
          "mediation": "AdMob",
          "package_version": "v3.0.0",
          "native_built_on": "v3.0.2",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Unity Android GAM",
          "framework": "Unity",
          "platform": "Android",
          "mediation": "GAM",
          "package_version": "v3.0.0",
          "native_built_on": "v3.0.2",
          "latest": false,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Unity Android AppLovin MAX",
          "framework": "Unity",
          "platform": "Android",
          "mediation": "AppLovin MAX",
          "package_version": "v2.1.11",
          "native_built_on": "v2.1.17",
          "latest": false,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Unity Android LevelPlay",
          "framework": "Unity",
          "platform": "Android",
          "mediation": "LevelPlay",
          "package_version": "v2.1.10",
          "native_built_on": "v2.1.18",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Unity iOS AdMob",
          "framework": "Unity",
          "platform": "iOS",
          "mediation": "AdMob",
          "package_version": "v3.0.0",
          "native_built_on": "v2.1.13",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_applicable",
              "confirmed": true,
              "note": "Platform-level feature, Android only.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Unity iOS GAM",
          "framework": "Unity",
          "platform": "iOS",
          "mediation": "GAM",
          "package_version": "v3.0.0",
          "native_built_on": "v2.1.13",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_applicable",
              "confirmed": true,
              "note": "Platform-level feature, Android only.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Unity iOS AppLovin MAX",
          "framework": "Unity",
          "platform": "iOS",
          "mediation": "AppLovin MAX",
          "package_version": "v2.1.11",
          "native_built_on": "v2.1.13",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_applicable",
              "confirmed": true,
              "note": "Platform-level feature, Android only.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Unity iOS LevelPlay",
          "framework": "Unity",
          "platform": "iOS",
          "mediation": "LevelPlay",
          "package_version": "v2.1.10",
          "native_built_on": "v2.1.11",
          "latest": false,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_applicable",
              "confirmed": true,
              "note": "Platform-level feature, Android only.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "React Native Android AdMob",
          "framework": "React Native",
          "platform": "Android",
          "mediation": "AdMob",
          "package_version": "v2.1.4",
          "native_built_on": "",
          "latest": false,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "React Native Android GAM",
          "framework": "React Native",
          "platform": "Android",
          "mediation": "GAM",
          "package_version": "v2.1.4",
          "native_built_on": "",
          "latest": false,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "React Native Android AppLovin MAX",
          "framework": "React Native",
          "platform": "Android",
          "mediation": "AppLovin MAX",
          "package_version": "v3.0.2",
          "native_built_on": "v3.0.0",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "React Native Android LevelPlay",
          "framework": "React Native",
          "platform": "Android",
          "mediation": "LevelPlay",
          "package_version": "v2.1.4",
          "native_built_on": "",
          "latest": false,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "React Native iOS AdMob",
          "framework": "React Native",
          "platform": "iOS",
          "mediation": "AdMob",
          "package_version": "v2.1.4",
          "native_built_on": "",
          "latest": false,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_applicable",
              "confirmed": true,
              "note": "Platform-level feature, Android only.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "React Native iOS GAM",
          "framework": "React Native",
          "platform": "iOS",
          "mediation": "GAM",
          "package_version": "v2.1.4",
          "native_built_on": "",
          "latest": false,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_applicable",
              "confirmed": true,
              "note": "Platform-level feature, Android only.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "React Native iOS AppLovin MAX",
          "framework": "React Native",
          "platform": "iOS",
          "mediation": "AppLovin MAX",
          "package_version": "v3.0.2",
          "native_built_on": "v3.0.2",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_applicable",
              "confirmed": true,
              "note": "Platform-level feature, Android only.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "React Native iOS LevelPlay",
          "framework": "React Native",
          "platform": "iOS",
          "mediation": "LevelPlay",
          "package_version": "v2.1.4",
          "native_built_on": "",
          "latest": false,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_applicable",
              "confirmed": true,
              "note": "Platform-level feature, Android only.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Cocos Android AdMob",
          "framework": "Cocos",
          "platform": "Android",
          "mediation": "AdMob",
          "package_version": "",
          "native_built_on": "",
          "latest": false,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Cocos Android GAM",
          "framework": "Cocos",
          "platform": "Android",
          "mediation": "GAM",
          "package_version": "",
          "native_built_on": "",
          "latest": false,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Cocos iOS AdMob",
          "framework": "Cocos",
          "platform": "iOS",
          "mediation": "AdMob",
          "package_version": "",
          "native_built_on": "",
          "latest": false,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_applicable",
              "confirmed": true,
              "note": "Platform-level feature, Android only.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-gma",
          "product_name": "Custom Adapter GMA SDK",
          "name": "Cocos iOS GAM",
          "framework": "Cocos",
          "platform": "iOS",
          "mediation": "GAM",
          "package_version": "",
          "native_built_on": "",
          "latest": false,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_applicable",
              "confirmed": true,
              "note": "Platform-level feature, Android only.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        }
      ]
    },
    {
      "id": "ca-ng",
      "name": "Custom Adapter GMA Next-Gen SDK",
      "package_count": 6,
      "packages": [
        {
          "product_id": "ca-ng",
          "product_name": "Custom Adapter GMA Next-Gen SDK",
          "name": "Native Android AdMob",
          "framework": "Native",
          "platform": "Android",
          "mediation": "AdMob",
          "package_version": "v2.0.2",
          "native_built_on": "",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-ng",
          "product_name": "Custom Adapter GMA Next-Gen SDK",
          "name": "Native Android GAM",
          "framework": "Native",
          "platform": "Android",
          "mediation": "GAM",
          "package_version": "v2.0.1",
          "native_built_on": "",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-ng",
          "product_name": "Custom Adapter GMA Next-Gen SDK",
          "name": "Native Android LevelPlay",
          "framework": "Native",
          "platform": "Android",
          "mediation": "LevelPlay",
          "package_version": "v2.0.0",
          "native_built_on": "",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-ng",
          "product_name": "Custom Adapter GMA Next-Gen SDK",
          "name": "Flutter Android AdMob",
          "framework": "Flutter",
          "platform": "Android",
          "mediation": "AdMob",
          "package_version": "v1.0.1",
          "native_built_on": "v2.0.2",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-ng",
          "product_name": "Custom Adapter GMA Next-Gen SDK",
          "name": "Unity Android AdMob",
          "framework": "Unity",
          "platform": "Android",
          "mediation": "AdMob",
          "package_version": "v2.0.0",
          "native_built_on": "v2.0.2",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        },
        {
          "product_id": "ca-ng",
          "product_name": "Custom Adapter GMA Next-Gen SDK",
          "name": "Unity Android LevelPlay",
          "framework": "Unity",
          "platform": "Android",
          "mediation": "LevelPlay",
          "package_version": "v2.0.0",
          "native_built_on": "v2.0.2",
          "latest": true,
          "features": {
            "crash_fix_threadlocal": {
              "status": "not_built",
              "confirmed": false,
              "note": "Pending release.",
              "display_name": "Android API 25 crash fix"
            },
            "discard_timeout_ad": {
              "status": "not_built",
              "confirmed": false,
              "note": "",
              "display_name": "Discard late ad after timeout no-fill"
            },
            "banner_ad_refresh": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad refresh"
            },
            "banner_ad_size_optimization": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Banner ad size optimization"
            },
            "updated_classnames": {
              "status": "shipped",
              "confirmed": true,
              "note": "",
              "display_name": "Standardized class names"
            }
          }
        }
      ]
    }
  ]
} as const;
